### ISSUE TITLE
Locale not found

### ISSUE THREAD

**Issue by CalvinScott** [nodeca/charlatan#13] opened 2015-07-31 23:32 UTC
For some reason I keep getting this error when installing the newest version.

/pipeline/build/node_modules/charlatan/lib/charlatan.js:86
      throw new Error('Locale not found:' + name);
            ^
Error: Locale not found:en-us
    at exports.addLocale (/pipeline/build/node_modules/charlatan/lib/charlatan.js:86:13)
    at Object.exports.setLocale (/pipeline/build/node_modules/charlatan/lib/charlatan.js:131:5)

**Comment by puzrin** [comment] 2015-07-31 23:40
try `en-US`, not `en-us`.

**Comment by puzrin** [comment] 2015-08-08 08:27
Closing - not a bug, wrong locale name in params.

**Closed by puzrin** 2015-08-08 08:27 UTC
